stages:
  parse_corpus:
    cmd: uv run python -m src.app.parse_corpus --corpus-dir data/raw/corpus --metadata data/raw/metadata.csv --occurrence data/raw/occurrences.csv --output data/interim/tokens.csv
    deps:
      - data/raw/occurrences.csv
      - data/raw/corpus
      - data/raw/metadata.csv
      - src/app/parse_corpus.py
      - src/infra/parser/textgrid_parser.py
    outs:
      - data/interim/tokens.csv

  extract_acoustics:
    cmd: uv run python -m src.app.extract_accoustics --input data/interim/tokens.csv --audio-dir data/raw/corpus --output data/processed/features_acoustic.csv
    deps:
      - data/interim/tokens.csv
      - data/raw/corpus
      - src/app/extract_accoustics.py
      - src/infra/extractor/praat_acoustic_extractor.py
    outs:
      - data/processed/features_acoustic.csv

  extract_neural_whisper:
    cmd: uv run python -m src.app.extract_neural --model whisper-medium --layers 1 12 24 --output data/processed/features_whisper.npz
    frozen: true
    deps:
      - data/interim/tokens.csv
      - src/app/extract_neural.py
      - src/infra/extractor/hugging_face_neural_extractor.py
    outs:
      - data/processed/features_whisper.npz

  extract_neural_xlsr:
    cmd: uv run python -m src.app.extract_neural --model xlsr-53 --layers 1 12 24 --output data/processed/features_xlsr.npz
    frozen: true
    deps:
      - data/interim/tokens.csv
      - src/app/extract_neural.py
      - src/infra/extractor/hugging_face_neural_extractor.py
    outs:
      - data/processed/features_xlsr.npz

  normalize:
    cmd: uv run python -m src.app.normalize
    outs:
      - data/processed/final_analysis_table.csv

  analyse:
    cmd:
      - uv run python -m src.app.analyse_descriptive
      - uv run python -m src.app.analyse_descriptive_boxplot
      - uv run python -m src.app.analyse_neural_comparaison
      - uv run python -m src.app.analyse_group_comparisons
      - uv run python -m src.app.analyse_inter_phoneme
      - uv run python -m src.app.analyse_loso_l1_l2
      - uv run python -m src.app.analyse_lme_strategy
      - uv run python -m src.app.analyse_ci_forest
      - uv run python -m src.app.analyse_neural_rope
      - uv run python -m src.app.analyse_rope
      - uv run python -m src.app.analyse_rope_summary
      - uv run python -m src.app.analyse_clustering
      - uv run python -m src.app.analyse_cv_clustering
      - uv run python -m src.app.analyse_speaker_clustering
      - uv run python -m src.app.analyse_visualize
      - uv run python -m src.app.analyse_stats
      - uv run python -m src.app.analyse_rsa
      - uv run python -m src.app.analyse_lme
    deps:
      - data/processed/final_analysis_table.csv
      - data/processed/features_whisper.npz
      - data/processed/features_xlsr.npz
      - src/app/analyse_visualize.py
      - src/app/analyse_stats.py
    outs:
      - results/figures/
    metrics:
      - results/stats_results.json:
          cache: false